// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpqh76tw2LwmCvAL1lMcFzr075C3YlF_k',
    appId: '1:1017407697366:web:4f114ef78a84b67cdcf477',
    messagingSenderId: '1017407697366',
    projectId: 'authjjk',
    authDomain: 'authjjk.firebaseapp.com',
    storageBucket: 'authjjk.appspot.com',
    measurementId: 'G-ZL47S9V07X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqwcTbnXKA6lyim9W3nawveWEphX_44Sc',
    appId: '1:1017407697366:android:a5172b004604d54bdcf477',
    messagingSenderId: '1017407697366',
    projectId: 'authjjk',
    storageBucket: 'authjjk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5tb9KcFg-fcLUThrkE3Z3TldFOQyJgq8',
    appId: '1:1017407697366:ios:832291fffe0e844cdcf477',
    messagingSenderId: '1017407697366',
    projectId: 'authjjk',
    storageBucket: 'authjjk.appspot.com',
    iosBundleId: 'com.example.jjk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5tb9KcFg-fcLUThrkE3Z3TldFOQyJgq8',
    appId: '1:1017407697366:ios:832291fffe0e844cdcf477',
    messagingSenderId: '1017407697366',
    projectId: 'authjjk',
    storageBucket: 'authjjk.appspot.com',
    iosBundleId: 'com.example.jjk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpqh76tw2LwmCvAL1lMcFzr075C3YlF_k',
    appId: '1:1017407697366:web:4f114ef78a84b67cdcf477',
    messagingSenderId: '1017407697366',
    projectId: 'authjjk',
    authDomain: 'authjjk.firebaseapp.com',
    storageBucket: 'authjjk.appspot.com',
    measurementId: 'G-ZL47S9V07X',
  );
}
